apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: ifedaniel-com-tls
spec:
  secretName: ifedaniel-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ifedaniel.com
  dnsNames:
    - ifedaniel.com
    - www.ifedaniel.com