apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: ifedan-com-tls
spec:
  secretName: ifedan-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ifedan.com
  dnsNames:
    - ifedan.com
    - www.ifedan.com